{% set name = "typical" %}
{% set version = "2.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typical-{{ version }}.tar.gz
  sha256: b8fcf86dce410c59cedd0c4a2a80d1b70e11bbe6fe343b81bfa5b303eedc5343

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1
    - python >=3.8.1,<4.0
  run:
    - inflection >=0.5,<0.6
    - pendulum >=3,<4
    - typing-extensions >=4,>5
    - pandas >=2.0,<3.0
    - future_typing >=0.4.1,<0.5.0
    - python >=3.8.1,<4.0

test:
  imports:
    - typic
    - typic.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seandstewart/typical
  summary: "Typical: Python's Typing Toolkit."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
